package rpg.beans;

import rpg.core.CharacterField;
import rpg.core.DecimalField;
import rpg.core.MessageField;
import rpg.core.MessageRecord;

import java.io.*;
import java.math.*;

import java.util.*;

/**
* Class generated by AS/400 CRTCLASS command from EDL094001 physical file definition.
* 
* File level identifier is 1220901095200.
* Record format level identifier is 43F66339AEE6B.
*/

public class EDL094001Message extends MessageRecord
{
  final static String fldnames[] = {
                                     "H01USERID",
                                     "H01PROGRM",
                                     "H01TIMSYS",
                                     "H01SCRCOD",
                                     "H01OPECOD",
                                     "H01FLGMAS",
                                     "H01FLGWK1",
                                     "H01FLGWK2",
                                     "H01FLGWK3",
                                     "E01DEAACC",
                                     "E01DEAACD",
                                     "E01DEACUN",
                                     "E01CUSNA1",
                                     "E01DEAPRO",
                                     "E01DEABNK",
                                     "E01DEATYP",
                                     "E01DEABRN",
                                     "E01DEACCY",
                                     "E01DEAGLN",
                                     "E01DEACCN",
                                     "E01VENDTM",
                                     "E01VENDTD",
                                     "E01VENDTY"
                                   };
  final static String tnames[] = {
                                   "H01USERID",
                                   "H01PROGRM",
                                   "H01TIMSYS",
                                   "H01SCRCOD",
                                   "H01OPECOD",
                                   "H01FLGMAS",
                                   "H01FLGWK1",
                                   "H01FLGWK2",
                                   "H01FLGWK3",
                                   "E01DEAACC",
                                   "E01DEAACD",
                                   "E01DEACUN",
                                   "E01CUSNA1",
                                   "E01DEAPRO",
                                   "E01DEABNK",
                                   "E01DEATYP",
                                   "E01DEABRN",
                                   "E01DEACCY",
                                   "E01DEAGLN",
                                   "E01DEACCN",
                                   "E01VENDTM",
                                   "E01VENDTD",
                                   "E01VENDTY"
                                 };
  final static String fid = "1220901095200";
  final static String rid = "43F66339AEE6B";
  final static String fmtname = "EDL094001";
  final int FIELDCOUNT = 23;
  private static Hashtable tlookup = new Hashtable();
  private CharacterField fieldH01USERID = null;
  private CharacterField fieldH01PROGRM = null;
  private CharacterField fieldH01TIMSYS = null;
  private CharacterField fieldH01SCRCOD = null;
  private CharacterField fieldH01OPECOD = null;
  private CharacterField fieldH01FLGMAS = null;
  private CharacterField fieldH01FLGWK1 = null;
  private CharacterField fieldH01FLGWK2 = null;
  private CharacterField fieldH01FLGWK3 = null;
  private DecimalField fieldE01DEAACC = null;
  private CharacterField fieldE01DEAACD = null;
  private DecimalField fieldE01DEACUN = null;
  private CharacterField fieldE01CUSNA1 = null;
  private CharacterField fieldE01DEAPRO = null;
  private CharacterField fieldE01DEABNK = null;
  private CharacterField fieldE01DEATYP = null;
  private DecimalField fieldE01DEABRN = null;
  private CharacterField fieldE01DEACCY = null;
  private DecimalField fieldE01DEAGLN = null;
  private DecimalField fieldE01DEACCN = null;
  private DecimalField fieldE01VENDTM = null;
  private DecimalField fieldE01VENDTD = null;
  private DecimalField fieldE01VENDTY = null;

  /**
  * Constructor for EDL094001Message.
  */
  public EDL094001Message()
  {
    createFields();
    initialize();
  }

  /**
  * Create fields for this message.
  * This method implements the abstract method in the MessageRecord superclass.
  */
  protected void createFields()
  {
    recordsize = 182;
    fileid = fid;
    recordid = rid;
    message = new byte[getByteLength()];
    formatname = fmtname;
    fieldnames = fldnames;
    tagnames = tnames;
    fields = new MessageField[FIELDCOUNT];

    fields[0] = fieldH01USERID =
    new CharacterField(message, HEADERSIZE + 0, 10, "H01USERID");
    fields[1] = fieldH01PROGRM =
    new CharacterField(message, HEADERSIZE + 10, 10, "H01PROGRM");
    fields[2] = fieldH01TIMSYS =
    new CharacterField(message, HEADERSIZE + 20, 12, "H01TIMSYS");
    fields[3] = fieldH01SCRCOD =
    new CharacterField(message, HEADERSIZE + 32, 2, "H01SCRCOD");
    fields[4] = fieldH01OPECOD =
    new CharacterField(message, HEADERSIZE + 34, 4, "H01OPECOD");
    fields[5] = fieldH01FLGMAS =
    new CharacterField(message, HEADERSIZE + 38, 1, "H01FLGMAS");
    fields[6] = fieldH01FLGWK1 =
    new CharacterField(message, HEADERSIZE + 39, 1, "H01FLGWK1");
    fields[7] = fieldH01FLGWK2 =
    new CharacterField(message, HEADERSIZE + 40, 1, "H01FLGWK2");
    fields[8] = fieldH01FLGWK3 =
    new CharacterField(message, HEADERSIZE + 41, 1, "H01FLGWK3");
    fields[9] = fieldE01DEAACC =
    new DecimalField(message, HEADERSIZE + 42, 13, 0, "E01DEAACC");
    fields[10] = fieldE01DEAACD =
    new CharacterField(message, HEADERSIZE + 55, 2, "E01DEAACD");
    fields[11] = fieldE01DEACUN =
    new DecimalField(message, HEADERSIZE + 57, 10, 0, "E01DEACUN");
    fields[12] = fieldE01CUSNA1 =
    new CharacterField(message, HEADERSIZE + 67, 60, "E01CUSNA1");
    fields[13] = fieldE01DEAPRO =
    new CharacterField(message, HEADERSIZE + 127, 4, "E01DEAPRO");
    fields[14] = fieldE01DEABNK =
    new CharacterField(message, HEADERSIZE + 131, 2, "E01DEABNK");
    fields[15] = fieldE01DEATYP =
    new CharacterField(message, HEADERSIZE + 133, 4, "E01DEATYP");
    fields[16] = fieldE01DEABRN =
    new DecimalField(message, HEADERSIZE + 137, 5, 0, "E01DEABRN");
    fields[17] = fieldE01DEACCY =
    new CharacterField(message, HEADERSIZE + 142, 3, "E01DEACCY");
    fields[18] = fieldE01DEAGLN =
    new DecimalField(message, HEADERSIZE + 145, 17, 0, "E01DEAGLN");
    fields[19] = fieldE01DEACCN =
    new DecimalField(message, HEADERSIZE + 162, 9, 0, "E01DEACCN");
    fields[20] = fieldE01VENDTM =
    new DecimalField(message, HEADERSIZE + 171, 3, 0, "E01VENDTM");
    fields[21] = fieldE01VENDTD =
    new DecimalField(message, HEADERSIZE + 174, 3, 0, "E01VENDTD");
    fields[22] = fieldE01VENDTY =
    new DecimalField(message, HEADERSIZE + 177, 5, 0, "E01VENDTY");

    synchronized (tlookup)
    {
      if (tlookup.isEmpty())
      {
        for (int i = 0; i < tnames.length; i++)
          tlookup.put(tnames[i], new Integer(i));
      }
    }

    taglookup = tlookup;
  }

  /**
  * Set field H01USERID using a String value.
  */
  public void setH01USERID(String newvalue)
  {
    fieldH01USERID.setString(newvalue);
  }

  /**
  * Get value of field H01USERID as a String.
  */
  public String getH01USERID()
  {
    return fieldH01USERID.getString();
  }

  /**
  * Set field H01PROGRM using a String value.
  */
  public void setH01PROGRM(String newvalue)
  {
    fieldH01PROGRM.setString(newvalue);
  }

  /**
  * Get value of field H01PROGRM as a String.
  */
  public String getH01PROGRM()
  {
    return fieldH01PROGRM.getString();
  }

  /**
  * Set field H01TIMSYS using a String value.
  */
  public void setH01TIMSYS(String newvalue)
  {
    fieldH01TIMSYS.setString(newvalue);
  }

  /**
  * Get value of field H01TIMSYS as a String.
  */
  public String getH01TIMSYS()
  {
    return fieldH01TIMSYS.getString();
  }

  /**
  * Set field H01SCRCOD using a String value.
  */
  public void setH01SCRCOD(String newvalue)
  {
    fieldH01SCRCOD.setString(newvalue);
  }

  /**
  * Get value of field H01SCRCOD as a String.
  */
  public String getH01SCRCOD()
  {
    return fieldH01SCRCOD.getString();
  }

  /**
  * Set field H01OPECOD using a String value.
  */
  public void setH01OPECOD(String newvalue)
  {
    fieldH01OPECOD.setString(newvalue);
  }

  /**
  * Get value of field H01OPECOD as a String.
  */
  public String getH01OPECOD()
  {
    return fieldH01OPECOD.getString();
  }

  /**
  * Set field H01FLGMAS using a String value.
  */
  public void setH01FLGMAS(String newvalue)
  {
    fieldH01FLGMAS.setString(newvalue);
  }

  /**
  * Get value of field H01FLGMAS as a String.
  */
  public String getH01FLGMAS()
  {
    return fieldH01FLGMAS.getString();
  }

  /**
  * Set field H01FLGWK1 using a String value.
  */
  public void setH01FLGWK1(String newvalue)
  {
    fieldH01FLGWK1.setString(newvalue);
  }

  /**
  * Get value of field H01FLGWK1 as a String.
  */
  public String getH01FLGWK1()
  {
    return fieldH01FLGWK1.getString();
  }

  /**
  * Set field H01FLGWK2 using a String value.
  */
  public void setH01FLGWK2(String newvalue)
  {
    fieldH01FLGWK2.setString(newvalue);
  }

  /**
  * Get value of field H01FLGWK2 as a String.
  */
  public String getH01FLGWK2()
  {
    return fieldH01FLGWK2.getString();
  }

  /**
  * Set field H01FLGWK3 using a String value.
  */
  public void setH01FLGWK3(String newvalue)
  {
    fieldH01FLGWK3.setString(newvalue);
  }

  /**
  * Get value of field H01FLGWK3 as a String.
  */
  public String getH01FLGWK3()
  {
    return fieldH01FLGWK3.getString();
  }

  /**
  * Set field E01DEAACC using a String value.
  */
  public void setE01DEAACC(String newvalue)
  {
    fieldE01DEAACC.setString(newvalue);
  }

  /**
  * Get value of field E01DEAACC as a String.
  */
  public String getE01DEAACC()
  {
    return fieldE01DEAACC.getString();
  }

  /**
  * Set numeric field E01DEAACC using a BigDecimal value.
  */
  public void setE01DEAACC(BigDecimal newvalue)
  {
    fieldE01DEAACC.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E01DEAACC as a BigDecimal.
  */
  public BigDecimal getBigDecimalE01DEAACC()
  {
    return fieldE01DEAACC.getBigDecimal();
  }

  /**
  * Set field E01DEAACD using a String value.
  */
  public void setE01DEAACD(String newvalue)
  {
    fieldE01DEAACD.setString(newvalue);
  }

  /**
  * Get value of field E01DEAACD as a String.
  */
  public String getE01DEAACD()
  {
    return fieldE01DEAACD.getString();
  }

  /**
  * Set field E01DEACUN using a String value.
  */
  public void setE01DEACUN(String newvalue)
  {
    fieldE01DEACUN.setString(newvalue);
  }

  /**
  * Get value of field E01DEACUN as a String.
  */
  public String getE01DEACUN()
  {
    return fieldE01DEACUN.getString();
  }

  /**
  * Set numeric field E01DEACUN using a BigDecimal value.
  */
  public void setE01DEACUN(BigDecimal newvalue)
  {
    fieldE01DEACUN.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E01DEACUN as a BigDecimal.
  */
  public BigDecimal getBigDecimalE01DEACUN()
  {
    return fieldE01DEACUN.getBigDecimal();
  }

  /**
  * Set field E01CUSNA1 using a String value.
  */
  public void setE01CUSNA1(String newvalue)
  {
    fieldE01CUSNA1.setString(newvalue);
  }

  /**
  * Get value of field E01CUSNA1 as a String.
  */
  public String getE01CUSNA1()
  {
    return fieldE01CUSNA1.getString();
  }

  /**
  * Set field E01DEAPRO using a String value.
  */
  public void setE01DEAPRO(String newvalue)
  {
    fieldE01DEAPRO.setString(newvalue);
  }

  /**
  * Get value of field E01DEAPRO as a String.
  */
  public String getE01DEAPRO()
  {
    return fieldE01DEAPRO.getString();
  }

  /**
  * Set field E01DEABNK using a String value.
  */
  public void setE01DEABNK(String newvalue)
  {
    fieldE01DEABNK.setString(newvalue);
  }

  /**
  * Get value of field E01DEABNK as a String.
  */
  public String getE01DEABNK()
  {
    return fieldE01DEABNK.getString();
  }

  /**
  * Set field E01DEATYP using a String value.
  */
  public void setE01DEATYP(String newvalue)
  {
    fieldE01DEATYP.setString(newvalue);
  }

  /**
  * Get value of field E01DEATYP as a String.
  */
  public String getE01DEATYP()
  {
    return fieldE01DEATYP.getString();
  }

  /**
  * Set field E01DEABRN using a String value.
  */
  public void setE01DEABRN(String newvalue)
  {
    fieldE01DEABRN.setString(newvalue);
  }

  /**
  * Get value of field E01DEABRN as a String.
  */
  public String getE01DEABRN()
  {
    return fieldE01DEABRN.getString();
  }

  /**
  * Set numeric field E01DEABRN using a BigDecimal value.
  */
  public void setE01DEABRN(BigDecimal newvalue)
  {
    fieldE01DEABRN.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E01DEABRN as a BigDecimal.
  */
  public BigDecimal getBigDecimalE01DEABRN()
  {
    return fieldE01DEABRN.getBigDecimal();
  }

  /**
  * Set field E01DEACCY using a String value.
  */
  public void setE01DEACCY(String newvalue)
  {
    fieldE01DEACCY.setString(newvalue);
  }

  /**
  * Get value of field E01DEACCY as a String.
  */
  public String getE01DEACCY()
  {
    return fieldE01DEACCY.getString();
  }

  /**
  * Set field E01DEAGLN using a String value.
  */
  public void setE01DEAGLN(String newvalue)
  {
    fieldE01DEAGLN.setString(newvalue);
  }

  /**
  * Get value of field E01DEAGLN as a String.
  */
  public String getE01DEAGLN()
  {
    return fieldE01DEAGLN.getString();
  }

  /**
  * Set numeric field E01DEAGLN using a BigDecimal value.
  */
  public void setE01DEAGLN(BigDecimal newvalue)
  {
    fieldE01DEAGLN.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E01DEAGLN as a BigDecimal.
  */
  public BigDecimal getBigDecimalE01DEAGLN()
  {
    return fieldE01DEAGLN.getBigDecimal();
  }

  /**
  * Set field E01DEACCN using a String value.
  */
  public void setE01DEACCN(String newvalue)
  {
    fieldE01DEACCN.setString(newvalue);
  }

  /**
  * Get value of field E01DEACCN as a String.
  */
  public String getE01DEACCN()
  {
    return fieldE01DEACCN.getString();
  }

  /**
  * Set numeric field E01DEACCN using a BigDecimal value.
  */
  public void setE01DEACCN(BigDecimal newvalue)
  {
    fieldE01DEACCN.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E01DEACCN as a BigDecimal.
  */
  public BigDecimal getBigDecimalE01DEACCN()
  {
    return fieldE01DEACCN.getBigDecimal();
  }

  /**
  * Set field E01VENDTM using a String value.
  */
  public void setE01VENDTM(String newvalue)
  {
    fieldE01VENDTM.setString(newvalue);
  }

  /**
  * Get value of field E01VENDTM as a String.
  */
  public String getE01VENDTM()
  {
    return fieldE01VENDTM.getString();
  }

  /**
  * Set numeric field E01VENDTM using a BigDecimal value.
  */
  public void setE01VENDTM(BigDecimal newvalue)
  {
    fieldE01VENDTM.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E01VENDTM as a BigDecimal.
  */
  public BigDecimal getBigDecimalE01VENDTM()
  {
    return fieldE01VENDTM.getBigDecimal();
  }

  /**
  * Set field E01VENDTD using a String value.
  */
  public void setE01VENDTD(String newvalue)
  {
    fieldE01VENDTD.setString(newvalue);
  }

  /**
  * Get value of field E01VENDTD as a String.
  */
  public String getE01VENDTD()
  {
    return fieldE01VENDTD.getString();
  }

  /**
  * Set numeric field E01VENDTD using a BigDecimal value.
  */
  public void setE01VENDTD(BigDecimal newvalue)
  {
    fieldE01VENDTD.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E01VENDTD as a BigDecimal.
  */
  public BigDecimal getBigDecimalE01VENDTD()
  {
    return fieldE01VENDTD.getBigDecimal();
  }

  /**
  * Set field E01VENDTY using a String value.
  */
  public void setE01VENDTY(String newvalue)
  {
    fieldE01VENDTY.setString(newvalue);
  }

  /**
  * Get value of field E01VENDTY as a String.
  */
  public String getE01VENDTY()
  {
    return fieldE01VENDTY.getString();
  }

  /**
  * Set numeric field E01VENDTY using a BigDecimal value.
  */
  public void setE01VENDTY(BigDecimal newvalue)
  {
    fieldE01VENDTY.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E01VENDTY as a BigDecimal.
  */
  public BigDecimal getBigDecimalE01VENDTY()
  {
    return fieldE01VENDTY.getBigDecimal();
  }

}
