package rpg.beans;

//import datapro.eibs.sockets.*;
import java.io.*;
import java.math.*;

import java.util.*;

import rpg.core.CharacterField;
import rpg.core.DecimalField;
import rpg.core.MessageField;
import rpg.core.MessageRecord;

/**
* Class generated by AS/400 CRTCLASS command from ESD278301 physical file definition.
* 
* File level identifier is 1231220084327.
* Record format level identifier is 4BB089BFBA224.
*/

public class ESD278301Message extends MessageRecord
{
  final static String fldnames[] = {
                                     "H01USR",
                                     "H01PGM",
                                     "H01TIM",
                                     "H01SCR",
                                     "H01OPE",
                                     "H01MAS",
                                     "H01WK1",
                                     "H01WK2",
                                     "H01WK3",
                                     "H01NRE",
                                     "H01INI",
                                     "H01TTR",
                                     "E01CCCDIS",
                                     "E01CCCRGI",
                                     "E01CCCRGE",
                                     "E01CCCRGD",
                                     "E01CCCSTS",
                                     "E01CCCED",
                                     "E01CCCTIP",
                                     "E01CCCUSM",
                                     "E01CCCFEM",
                                     "E01CCCUSA",
                                     "E01CCCFEA",
                                     "E01CCCFED",
                                     "E01CCCMOV",
                                     "E01CCCMD",
                                     "E01CCCMDV",
                                     "E01CCECMO",
                                     "E01CCECNO",
                                     "E01CCESEQ",
                                     "E01CCETYD",
                                     "E01CCECID",
                                     "E01CCECNM",
                                     "E01CCECTI",
                                     "E01CCTID",
                                     "E01CCECMR",
                                     "E01CCECCU",
                                     "E01CCECPZ",
                                     "E01CCEEMA",
                                     "E01CCEPHN",
                                     "E01CCEDIS",
                                     "E01CCESTS",
                                     "E01CCEED",
                                     "E01CCEMOV",
                                     "E01CCEMD",
                                     "E01CCEDEN",
                                     "E01CCEFDI",
                                     "E01CCEFBE",
                                     "E01CCEFSE",
                                     "E01CCEFCC",
                                     "E01CCEFRC",
                                     "E01CCEFRE",
                                     "E01CCEECC",
                                     "E01CCERED",
                                     "E01CCEHIR",
                                     "E01CCEAC1",
                                     "E01CCEAC2",
                                     "E01CCEAC3",
                                     "E01CCEAC4",
                                     "E01CCDRMM",
                                     "E01CCDRDD",
                                     "E01CCDRYY",
                                     "E01CCDRUS",
                                     "E01CCDMMM",
                                     "E01CCDMDD",
                                     "E01CCDMYY",
                                     "E01CCDMTI",
                                     "E01CCDMUS"
                                   };
  final static String tnames[] = {
                                   "H01USR",
                                   "H01PGM",
                                   "H01TIM",
                                   "H01SCR",
                                   "H01OPE",
                                   "H01MAS",
                                   "H01WK1",
                                   "H01WK2",
                                   "H01WK3",
                                   "H01NRE",
                                   "H01INI",
                                   "H01TTR",
                                   "E01CCCDIS",
                                   "E01CCCRGI",
                                   "E01CCCRGE",
                                   "E01CCCRGD",
                                   "E01CCCSTS",
                                   "E01CCCED",
                                   "E01CCCTIP",
                                   "E01CCCUSM",
                                   "E01CCCFEM",
                                   "E01CCCUSA",
                                   "E01CCCFEA",
                                   "E01CCCFED",
                                   "E01CCCMOV",
                                   "E01CCCMD",
                                   "E01CCCMDV",
                                   "E01CCECMO",
                                   "E01CCECNO",
                                   "E01CCESEQ",
                                   "E01CCETYD",
                                   "E01CCECID",
                                   "E01CCECNM",
                                   "E01CCECTI",
                                   "E01CCTID",
                                   "E01CCECMR",
                                   "E01CCECCU",
                                   "E01CCECPZ",
                                   "E01CCEEMA",
                                   "E01CCEPHN",
                                   "E01CCEDIS",
                                   "E01CCESTS",
                                   "E01CCEED",
                                   "E01CCEMOV",
                                   "E01CCEMD",
                                   "E01CCEDEN",
                                   "E01CCEFDI",
                                   "E01CCEFBE",
                                   "E01CCEFSE",
                                   "E01CCEFCC",
                                   "E01CCEFRC",
                                   "E01CCEFRE",
                                   "E01CCEECC",
                                   "E01CCERED",
                                   "E01CCEHIR",
                                   "E01CCEAC1",
                                   "E01CCEAC2",
                                   "E01CCEAC3",
                                   "E01CCEAC4",
                                   "E01CCDRMM",
                                   "E01CCDRDD",
                                   "E01CCDRYY",
                                   "E01CCDRUS",
                                   "E01CCDMMM",
                                   "E01CCDMDD",
                                   "E01CCDMYY",
                                   "E01CCDMTI",
                                   "E01CCDMUS"
                                 };
  final static String fid = "1231220084327";
  final static String rid = "4BB089BFBA224";
  final static String fmtname = "ESD278301";
  final int FIELDCOUNT = 68;
  private static Hashtable tlookup = new Hashtable();
  private CharacterField fieldH01USR = null;
  private CharacterField fieldH01PGM = null;
  private CharacterField fieldH01TIM = null;
  private CharacterField fieldH01SCR = null;
  private CharacterField fieldH01OPE = null;
  private CharacterField fieldH01MAS = null;
  private CharacterField fieldH01WK1 = null;
  private CharacterField fieldH01WK2 = null;
  private CharacterField fieldH01WK3 = null;
  private DecimalField fieldH01NRE = null;
  private DecimalField fieldH01INI = null;
  private DecimalField fieldH01TTR = null;
  private CharacterField fieldE01CCCDIS = null;
  private DecimalField fieldE01CCCRGI = null;
  private DecimalField fieldE01CCCRGE = null;
  private DecimalField fieldE01CCCRGD = null;
  private CharacterField fieldE01CCCSTS = null;
  private CharacterField fieldE01CCCED = null;
  private CharacterField fieldE01CCCTIP = null;
  private CharacterField fieldE01CCCUSM = null;
  private DecimalField fieldE01CCCFEM = null;
  private CharacterField fieldE01CCCUSA = null;
  private DecimalField fieldE01CCCFEA = null;
  private DecimalField fieldE01CCCFED = null;
  private CharacterField fieldE01CCCMOV = null;
  private CharacterField fieldE01CCCMD = null;
  private CharacterField fieldE01CCCMDV = null;
  private CharacterField fieldE01CCECMO = null;
  private DecimalField fieldE01CCECNO = null;
  private DecimalField fieldE01CCESEQ = null;
  private CharacterField fieldE01CCETYD = null;
  private CharacterField fieldE01CCECID = null;
  private CharacterField fieldE01CCECNM = null;
  private CharacterField fieldE01CCECTI = null;
  private CharacterField fieldE01CCTID = null;
  private CharacterField fieldE01CCECMR = null;
  private DecimalField fieldE01CCECCU = null;
  private CharacterField fieldE01CCECPZ = null;
  private CharacterField fieldE01CCEEMA = null;
  private CharacterField fieldE01CCEPHN = null;
  private CharacterField fieldE01CCEDIS = null;
  private CharacterField fieldE01CCESTS = null;
  private CharacterField fieldE01CCEED = null;
  private CharacterField fieldE01CCEMOV = null;
  private CharacterField fieldE01CCEMD = null;
  private CharacterField fieldE01CCEDEN = null;
  private DecimalField fieldE01CCEFDI = null;
  private DecimalField fieldE01CCEFBE = null;
  private DecimalField fieldE01CCEFSE = null;
  private DecimalField fieldE01CCEFCC = null;
  private DecimalField fieldE01CCEFRC = null;
  private DecimalField fieldE01CCEFRE = null;
  private CharacterField fieldE01CCEECC = null;
  private CharacterField fieldE01CCERED = null;
  private CharacterField fieldE01CCEHIR = null;
  private CharacterField fieldE01CCEAC1 = null;
  private CharacterField fieldE01CCEAC2 = null;
  private DecimalField fieldE01CCEAC3 = null;
  private DecimalField fieldE01CCEAC4 = null;
  private DecimalField fieldE01CCDRMM = null;
  private DecimalField fieldE01CCDRDD = null;
  private DecimalField fieldE01CCDRYY = null;
  private CharacterField fieldE01CCDRUS = null;
  private DecimalField fieldE01CCDMMM = null;
  private DecimalField fieldE01CCDMDD = null;
  private DecimalField fieldE01CCDMYY = null;
  private CharacterField fieldE01CCDMTI = null;
  private CharacterField fieldE01CCDMUS = null;

  /**
  * Constructor for ESD278301Message.
  */
  public ESD278301Message()
  {
    createFields();
    initialize();
  }

  /**
  * Create fields for this message.
  * This method implements the abstract method in the MessageRecord superclass.
  */
  protected void createFields()
  {
    recordsize = 1271;
    fileid = fid;
    recordid = rid;
    message = new byte[getByteLength()];
    formatname = fmtname;
    fieldnames = fldnames;
    tagnames = tnames;
      fields = new MessageField[FIELDCOUNT];

    fields[0] = fieldH01USR =
    new CharacterField(message, HEADERSIZE + 0, 10, "H01USR");
    fields[1] = fieldH01PGM =
    new CharacterField(message, HEADERSIZE + 10, 10, "H01PGM");
    fields[2] = fieldH01TIM =
    new CharacterField(message, HEADERSIZE + 20, 12, "H01TIM");
    fields[3] = fieldH01SCR =
    new CharacterField(message, HEADERSIZE + 32, 2, "H01SCR");
    fields[4] = fieldH01OPE =
    new CharacterField(message, HEADERSIZE + 34, 4, "H01OPE");
    fields[5] = fieldH01MAS =
    new CharacterField(message, HEADERSIZE + 38, 1, "H01MAS");
    fields[6] = fieldH01WK1 =
    new CharacterField(message, HEADERSIZE + 39, 1, "H01WK1");
    fields[7] = fieldH01WK2 =
    new CharacterField(message, HEADERSIZE + 40, 1, "H01WK2");
    fields[8] = fieldH01WK3 =
    new CharacterField(message, HEADERSIZE + 41, 1, "H01WK3");
    fields[9] = fieldH01NRE =
    new DecimalField(message, HEADERSIZE + 42, 10, 0, "H01NRE");
    fields[10] = fieldH01INI =
    new DecimalField(message, HEADERSIZE + 52, 10, 0, "H01INI");
    fields[11] = fieldH01TTR =
    new DecimalField(message, HEADERSIZE + 62, 10, 0, "H01TTR");
    fields[12] = fieldE01CCCDIS =
    new CharacterField(message, HEADERSIZE + 72, 4, "E01CCCDIS");
    fields[13] = fieldE01CCCRGI =
    new DecimalField(message, HEADERSIZE + 76, 10, 0, "E01CCCRGI");
    fields[14] = fieldE01CCCRGE =
    new DecimalField(message, HEADERSIZE + 86, 10, 0, "E01CCCRGE");
    fields[15] = fieldE01CCCRGD =
    new DecimalField(message, HEADERSIZE + 96, 10, 0, "E01CCCRGD");
    fields[16] = fieldE01CCCSTS =
    new CharacterField(message, HEADERSIZE + 106, 2, "E01CCCSTS");
    fields[17] = fieldE01CCCED =
    new CharacterField(message, HEADERSIZE + 108, 45, "E01CCCED");
    fields[18] = fieldE01CCCTIP =
    new CharacterField(message, HEADERSIZE + 153, 10, "E01CCCTIP");
    fields[19] = fieldE01CCCUSM =
    new CharacterField(message, HEADERSIZE + 163, 10, "E01CCCUSM");
    fields[20] = fieldE01CCCFEM =
    new DecimalField(message, HEADERSIZE + 173, 9, 0, "E01CCCFEM");
    fields[21] = fieldE01CCCUSA =
    new CharacterField(message, HEADERSIZE + 182, 10, "E01CCCUSA");
    fields[22] = fieldE01CCCFEA =
    new DecimalField(message, HEADERSIZE + 192, 9, 0, "E01CCCFEA");
    fields[23] = fieldE01CCCFED =
    new DecimalField(message, HEADERSIZE + 201, 9, 0, "E01CCCFED");
    fields[24] = fieldE01CCCMOV =
    new CharacterField(message, HEADERSIZE + 210, 2, "E01CCCMOV");
    fields[25] = fieldE01CCCMD =
    new CharacterField(message, HEADERSIZE + 212, 45, "E01CCCMD");
    fields[26] = fieldE01CCCMDV =
    new CharacterField(message, HEADERSIZE + 257, 250, "E01CCCMDV");
    fields[27] = fieldE01CCECMO =
    new CharacterField(message, HEADERSIZE + 507, 2, "E01CCECMO");
    fields[28] = fieldE01CCECNO =
    new DecimalField(message, HEADERSIZE + 509, 10, 0, "E01CCECNO");
    fields[29] = fieldE01CCESEQ =
    new DecimalField(message, HEADERSIZE + 519, 10, 0, "E01CCESEQ");
    fields[30] = fieldE01CCETYD =
    new CharacterField(message, HEADERSIZE + 529, 1, "E01CCETYD");
    fields[31] = fieldE01CCECID =
    new CharacterField(message, HEADERSIZE + 530, 13, "E01CCECID");
    fields[32] = fieldE01CCECNM =
    new CharacterField(message, HEADERSIZE + 543, 150, "E01CCECNM");
    fields[33] = fieldE01CCECTI =
    new CharacterField(message, HEADERSIZE + 693, 40, "E01CCECTI");
    fields[34] = fieldE01CCTID =
    new CharacterField(message, HEADERSIZE + 733, 45, "E01CCTID");
    fields[35] = fieldE01CCECMR =
    new CharacterField(message, HEADERSIZE + 778, 20, "E01CCECMR");
    fields[36] = fieldE01CCECCU =
    new DecimalField(message, HEADERSIZE + 798, 18, 2, "E01CCECCU");
    fields[37] = fieldE01CCECPZ =
    new CharacterField(message, HEADERSIZE + 816, 50, "E01CCECPZ");
    fields[38] = fieldE01CCEEMA =
    new CharacterField(message, HEADERSIZE + 866, 60, "E01CCEEMA");
    fields[39] = fieldE01CCEPHN =
    new CharacterField(message, HEADERSIZE + 926, 12, "E01CCEPHN");
    fields[40] = fieldE01CCEDIS =
    new CharacterField(message, HEADERSIZE + 938, 4, "E01CCEDIS");
    fields[41] = fieldE01CCESTS =
    new CharacterField(message, HEADERSIZE + 942, 2, "E01CCESTS");
    fields[42] = fieldE01CCEED =
    new CharacterField(message, HEADERSIZE + 944, 45, "E01CCEED");
    fields[43] = fieldE01CCEMOV =
    new CharacterField(message, HEADERSIZE + 989, 2, "E01CCEMOV");
    fields[44] = fieldE01CCEMD =
    new CharacterField(message, HEADERSIZE + 991, 45, "E01CCEMD");
    fields[45] = fieldE01CCEDEN =
    new CharacterField(message, HEADERSIZE + 1036, 2, "E01CCEDEN");
    fields[46] = fieldE01CCEFDI =
    new DecimalField(message, HEADERSIZE + 1038, 9, 0, "E01CCEFDI");
    fields[47] = fieldE01CCEFBE =
    new DecimalField(message, HEADERSIZE + 1047, 9, 0, "E01CCEFBE");
    fields[48] = fieldE01CCEFSE =
    new DecimalField(message, HEADERSIZE + 1056, 9, 0, "E01CCEFSE");
    fields[49] = fieldE01CCEFCC =
    new DecimalField(message, HEADERSIZE + 1065, 9, 0, "E01CCEFCC");
    fields[50] = fieldE01CCEFRC =
    new DecimalField(message, HEADERSIZE + 1074, 9, 0, "E01CCEFRC");
    fields[51] = fieldE01CCEFRE =
    new DecimalField(message, HEADERSIZE + 1083, 9, 0, "E01CCEFRE");
    fields[52] = fieldE01CCEECC =
    new CharacterField(message, HEADERSIZE + 1092, 2, "E01CCEECC");
    fields[53] = fieldE01CCERED =
    new CharacterField(message, HEADERSIZE + 1094, 2, "E01CCERED");
    fields[54] = fieldE01CCEHIR =
    new CharacterField(message, HEADERSIZE + 1096, 40, "E01CCEHIR");
    fields[55] = fieldE01CCEAC1 =
    new CharacterField(message, HEADERSIZE + 1136, 10, "E01CCEAC1");
    fields[56] = fieldE01CCEAC2 =
    new CharacterField(message, HEADERSIZE + 1146, 30, "E01CCEAC2");
    fields[57] = fieldE01CCEAC3 =
    new DecimalField(message, HEADERSIZE + 1176, 9, 0, "E01CCEAC3");
    fields[58] = fieldE01CCEAC4 =
    new DecimalField(message, HEADERSIZE + 1185, 18, 2, "E01CCEAC4");
    fields[59] = fieldE01CCDRMM =
    new DecimalField(message, HEADERSIZE + 1203, 3, 0, "E01CCDRMM");
    fields[60] = fieldE01CCDRDD =
    new DecimalField(message, HEADERSIZE + 1206, 3, 0, "E01CCDRDD");
    fields[61] = fieldE01CCDRYY =
    new DecimalField(message, HEADERSIZE + 1209, 5, 0, "E01CCDRYY");
    fields[62] = fieldE01CCDRUS =
    new CharacterField(message, HEADERSIZE + 1214, 10, "E01CCDRUS");
    fields[63] = fieldE01CCDMMM =
    new DecimalField(message, HEADERSIZE + 1224, 3, 0, "E01CCDMMM");
    fields[64] = fieldE01CCDMDD =
    new DecimalField(message, HEADERSIZE + 1227, 3, 0, "E01CCDMDD");
    fields[65] = fieldE01CCDMYY =
    new DecimalField(message, HEADERSIZE + 1230, 5, 0, "E01CCDMYY");
    fields[66] = fieldE01CCDMTI =
    new CharacterField(message, HEADERSIZE + 1235, 26, "E01CCDMTI");
    fields[67] = fieldE01CCDMUS =
    new CharacterField(message, HEADERSIZE + 1261, 10, "E01CCDMUS");

    synchronized (tlookup)
    {
      if (tlookup.isEmpty())
      {
        for (int i = 0; i < tnames.length; i++)
        tlookup.put(tnames[i], new Integer(i));
      }
    }

    taglookup = tlookup;
  }

  /**
  * Set field H01USR using a String value.
  */
  public void setH01USR(String newvalue)
  {
    fieldH01USR.setString(newvalue);
  }

  /**
  * Get value of field H01USR as a String.
  */
  public String getH01USR()
  {
    return fieldH01USR.getString();
  }

  /**
  * Set field H01PGM using a String value.
  */
  public void setH01PGM(String newvalue)
  {
    fieldH01PGM.setString(newvalue);
  }

  /**
  * Get value of field H01PGM as a String.
  */
  public String getH01PGM()
  {
    return fieldH01PGM.getString();
  }

  /**
  * Set field H01TIM using a String value.
  */
  public void setH01TIM(String newvalue)
  {
    fieldH01TIM.setString(newvalue);
  }

  /**
  * Get value of field H01TIM as a String.
  */
  public String getH01TIM()
  {
    return fieldH01TIM.getString();
  }

  /**
  * Set field H01SCR using a String value.
  */
  public void setH01SCR(String newvalue)
  {
    fieldH01SCR.setString(newvalue);
  }

  /**
  * Get value of field H01SCR as a String.
  */
  public String getH01SCR()
  {
    return fieldH01SCR.getString();
  }

  /**
  * Set field H01OPE using a String value.
  */
  public void setH01OPE(String newvalue)
  {
    fieldH01OPE.setString(newvalue);
  }

  /**
  * Get value of field H01OPE as a String.
  */
  public String getH01OPE()
  {
    return fieldH01OPE.getString();
  }

  /**
  * Set field H01MAS using a String value.
  */
  public void setH01MAS(String newvalue)
  {
    fieldH01MAS.setString(newvalue);
  }

  /**
  * Get value of field H01MAS as a String.
  */
  public String getH01MAS()
  {
    return fieldH01MAS.getString();
  }

  /**
  * Set field H01WK1 using a String value.
  */
  public void setH01WK1(String newvalue)
  {
    fieldH01WK1.setString(newvalue);
  }

  /**
  * Get value of field H01WK1 as a String.
  */
  public String getH01WK1()
  {
    return fieldH01WK1.getString();
  }

  /**
  * Set field H01WK2 using a String value.
  */
  public void setH01WK2(String newvalue)
  {
    fieldH01WK2.setString(newvalue);
  }

  /**
  * Get value of field H01WK2 as a String.
  */
  public String getH01WK2()
  {
    return fieldH01WK2.getString();
  }

  /**
  * Set field H01WK3 using a String value.
  */
  public void setH01WK3(String newvalue)
  {
    fieldH01WK3.setString(newvalue);
  }

  /**
  * Get value of field H01WK3 as a String.
  */
  public String getH01WK3()
  {
    return fieldH01WK3.getString();
  }

  /**
  * Set field H01NRE using a String value.
  */
  public void setH01NRE(String newvalue)
  {
    fieldH01NRE.setString(newvalue);
  }

  /**
  * Get value of field H01NRE as a String.
  */
  public String getH01NRE()
  {
    return fieldH01NRE.getString();
  }

  /**
  * Set numeric field H01NRE using a BigDecimal value.
  */
  public void setH01NRE(BigDecimal newvalue)
  {
    fieldH01NRE.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field H01NRE as a BigDecimal.
  */
  public BigDecimal getBigDecimalH01NRE()
  {
    return fieldH01NRE.getBigDecimal();
  }

  /**
  * Set field H01INI using a String value.
  */
  public void setH01INI(String newvalue)
  {
    fieldH01INI.setString(newvalue);
  }

  /**
  * Get value of field H01INI as a String.
  */
  public String getH01INI()
  {
    return fieldH01INI.getString();
  }

  /**
  * Set numeric field H01INI using a BigDecimal value.
  */
  public void setH01INI(BigDecimal newvalue)
  {
    fieldH01INI.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field H01INI as a BigDecimal.
  */
  public BigDecimal getBigDecimalH01INI()
  {
    return fieldH01INI.getBigDecimal();
  }

  /**
  * Set field H01TTR using a String value.
  */
  public void setH01TTR(String newvalue)
  {
    fieldH01TTR.setString(newvalue);
  }

  /**
  * Get value of field H01TTR as a String.
  */
  public String getH01TTR()
  {
    return fieldH01TTR.getString();
  }

  /**
  * Set numeric field H01TTR using a BigDecimal value.
  */
  public void setH01TTR(BigDecimal newvalue)
  {
    fieldH01TTR.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field H01TTR as a BigDecimal.
  */
  public BigDecimal getBigDecimalH01TTR()
  {
    return fieldH01TTR.getBigDecimal();
  }

  /**
  * Set field E01CCCDIS using a String value.
  */
  public void setE01CCCDIS(String newvalue)
  {
    fieldE01CCCDIS.setString(newvalue);
  }

  /**
  * Get value of field E01CCCDIS as a String.
  */
  public String getE01CCCDIS()
  {
    return fieldE01CCCDIS.getString();
  }

  /**
  * Set field E01CCCRGI using a String value.
  */
  public void setE01CCCRGI(String newvalue)
  {
    fieldE01CCCRGI.setString(newvalue);
  }

  /**
  * Get value of field E01CCCRGI as a String.
  */
  public String getE01CCCRGI()
  {
    return fieldE01CCCRGI.getString();
  }

  /**
  * Set numeric field E01CCCRGI using a BigDecimal value.
  */
  public void setE01CCCRGI(BigDecimal newvalue)
  {
    fieldE01CCCRGI.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E01CCCRGI as a BigDecimal.
  */
  public BigDecimal getBigDecimalE01CCCRGI()
  {
    return fieldE01CCCRGI.getBigDecimal();
  }

  /**
  * Set field E01CCCRGE using a String value.
  */
  public void setE01CCCRGE(String newvalue)
  {
    fieldE01CCCRGE.setString(newvalue);
  }

  /**
  * Get value of field E01CCCRGE as a String.
  */
  public String getE01CCCRGE()
  {
    return fieldE01CCCRGE.getString();
  }

  /**
  * Set numeric field E01CCCRGE using a BigDecimal value.
  */
  public void setE01CCCRGE(BigDecimal newvalue)
  {
    fieldE01CCCRGE.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E01CCCRGE as a BigDecimal.
  */
  public BigDecimal getBigDecimalE01CCCRGE()
  {
    return fieldE01CCCRGE.getBigDecimal();
  }

  /**
  * Set field E01CCCRGD using a String value.
  */
  public void setE01CCCRGD(String newvalue)
  {
    fieldE01CCCRGD.setString(newvalue);
  }

  /**
  * Get value of field E01CCCRGD as a String.
  */
  public String getE01CCCRGD()
  {
    return fieldE01CCCRGD.getString();
  }

  /**
  * Set numeric field E01CCCRGD using a BigDecimal value.
  */
  public void setE01CCCRGD(BigDecimal newvalue)
  {
    fieldE01CCCRGD.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E01CCCRGD as a BigDecimal.
  */
  public BigDecimal getBigDecimalE01CCCRGD()
  {
    return fieldE01CCCRGD.getBigDecimal();
  }

  /**
  * Set field E01CCCSTS using a String value.
  */
  public void setE01CCCSTS(String newvalue)
  {
    fieldE01CCCSTS.setString(newvalue);
  }

  /**
  * Get value of field E01CCCSTS as a String.
  */
  public String getE01CCCSTS()
  {
    return fieldE01CCCSTS.getString();
  }

  /**
  * Set field E01CCCED using a String value.
  */
  public void setE01CCCED(String newvalue)
  {
    fieldE01CCCED.setString(newvalue);
  }

  /**
  * Get value of field E01CCCED as a String.
  */
  public String getE01CCCED()
  {
    return fieldE01CCCED.getString();
  }

  /**
  * Set field E01CCCTIP using a String value.
  */
  public void setE01CCCTIP(String newvalue)
  {
    fieldE01CCCTIP.setString(newvalue);
  }

  /**
  * Get value of field E01CCCTIP as a String.
  */
  public String getE01CCCTIP()
  {
    return fieldE01CCCTIP.getString();
  }

  /**
  * Set field E01CCCUSM using a String value.
  */
  public void setE01CCCUSM(String newvalue)
  {
    fieldE01CCCUSM.setString(newvalue);
  }

  /**
  * Get value of field E01CCCUSM as a String.
  */
  public String getE01CCCUSM()
  {
    return fieldE01CCCUSM.getString();
  }

  /**
  * Set field E01CCCFEM using a String value.
  */
  public void setE01CCCFEM(String newvalue)
  {
    fieldE01CCCFEM.setString(newvalue);
  }

  /**
  * Get value of field E01CCCFEM as a String.
  */
  public String getE01CCCFEM()
  {
    return fieldE01CCCFEM.getString();
  }

  /**
  * Set numeric field E01CCCFEM using a BigDecimal value.
  */
  public void setE01CCCFEM(BigDecimal newvalue)
  {
    fieldE01CCCFEM.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E01CCCFEM as a BigDecimal.
  */
  public BigDecimal getBigDecimalE01CCCFEM()
  {
    return fieldE01CCCFEM.getBigDecimal();
  }

  /**
  * Set field E01CCCUSA using a String value.
  */
  public void setE01CCCUSA(String newvalue)
  {
    fieldE01CCCUSA.setString(newvalue);
  }

  /**
  * Get value of field E01CCCUSA as a String.
  */
  public String getE01CCCUSA()
  {
    return fieldE01CCCUSA.getString();
  }

  /**
  * Set field E01CCCFEA using a String value.
  */
  public void setE01CCCFEA(String newvalue)
  {
    fieldE01CCCFEA.setString(newvalue);
  }

  /**
  * Get value of field E01CCCFEA as a String.
  */
  public String getE01CCCFEA()
  {
    return fieldE01CCCFEA.getString();
  }

  /**
  * Set numeric field E01CCCFEA using a BigDecimal value.
  */
  public void setE01CCCFEA(BigDecimal newvalue)
  {
    fieldE01CCCFEA.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E01CCCFEA as a BigDecimal.
  */
  public BigDecimal getBigDecimalE01CCCFEA()
  {
    return fieldE01CCCFEA.getBigDecimal();
  }

  /**
  * Set field E01CCCFED using a String value.
  */
  public void setE01CCCFED(String newvalue)
  {
    fieldE01CCCFED.setString(newvalue);
  }

  /**
  * Get value of field E01CCCFED as a String.
  */
  public String getE01CCCFED()
  {
    return fieldE01CCCFED.getString();
  }

  /**
  * Set numeric field E01CCCFED using a BigDecimal value.
  */
  public void setE01CCCFED(BigDecimal newvalue)
  {
    fieldE01CCCFED.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E01CCCFED as a BigDecimal.
  */
  public BigDecimal getBigDecimalE01CCCFED()
  {
    return fieldE01CCCFED.getBigDecimal();
  }

  /**
  * Set field E01CCCMOV using a String value.
  */
  public void setE01CCCMOV(String newvalue)
  {
    fieldE01CCCMOV.setString(newvalue);
  }

  /**
  * Get value of field E01CCCMOV as a String.
  */
  public String getE01CCCMOV()
  {
    return fieldE01CCCMOV.getString();
  }

  /**
  * Set field E01CCCMD using a String value.
  */
  public void setE01CCCMD(String newvalue)
  {
    fieldE01CCCMD.setString(newvalue);
  }

  /**
  * Get value of field E01CCCMD as a String.
  */
  public String getE01CCCMD()
  {
    return fieldE01CCCMD.getString();
  }

  /**
  * Set field E01CCCMDV using a String value.
  */
  public void setE01CCCMDV(String newvalue)
  {
    fieldE01CCCMDV.setString(newvalue);
  }

  /**
  * Get value of field E01CCCMDV as a String.
  */
  public String getE01CCCMDV()
  {
    return fieldE01CCCMDV.getString();
  }

  /**
  * Set field E01CCECMO using a String value.
  */
  public void setE01CCECMO(String newvalue)
  {
    fieldE01CCECMO.setString(newvalue);
  }

  /**
  * Get value of field E01CCECMO as a String.
  */
  public String getE01CCECMO()
  {
    return fieldE01CCECMO.getString();
  }

  /**
  * Set field E01CCECNO using a String value.
  */
  public void setE01CCECNO(String newvalue)
  {
    fieldE01CCECNO.setString(newvalue);
  }

  /**
  * Get value of field E01CCECNO as a String.
  */
  public String getE01CCECNO()
  {
    return fieldE01CCECNO.getString();
  }

  /**
  * Set numeric field E01CCECNO using a BigDecimal value.
  */
  public void setE01CCECNO(BigDecimal newvalue)
  {
    fieldE01CCECNO.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E01CCECNO as a BigDecimal.
  */
  public BigDecimal getBigDecimalE01CCECNO()
  {
    return fieldE01CCECNO.getBigDecimal();
  }

  /**
  * Set field E01CCESEQ using a String value.
  */
  public void setE01CCESEQ(String newvalue)
  {
    fieldE01CCESEQ.setString(newvalue);
  }

  /**
  * Get value of field E01CCESEQ as a String.
  */
  public String getE01CCESEQ()
  {
    return fieldE01CCESEQ.getString();
  }

  /**
  * Set numeric field E01CCESEQ using a BigDecimal value.
  */
  public void setE01CCESEQ(BigDecimal newvalue)
  {
    fieldE01CCESEQ.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E01CCESEQ as a BigDecimal.
  */
  public BigDecimal getBigDecimalE01CCESEQ()
  {
    return fieldE01CCESEQ.getBigDecimal();
  }

  /**
  * Set field E01CCETYD using a String value.
  */
  public void setE01CCETYD(String newvalue)
  {
    fieldE01CCETYD.setString(newvalue);
  }

  /**
  * Get value of field E01CCETYD as a String.
  */
  public String getE01CCETYD()
  {
    return fieldE01CCETYD.getString();
  }

  /**
  * Set field E01CCECID using a String value.
  */
  public void setE01CCECID(String newvalue)
  {
    fieldE01CCECID.setString(newvalue);
  }

  /**
  * Get value of field E01CCECID as a String.
  */
  public String getE01CCECID()
  {
    return fieldE01CCECID.getString();
  }

  /**
  * Set field E01CCECNM using a String value.
  */
  public void setE01CCECNM(String newvalue)
  {
    fieldE01CCECNM.setString(newvalue);
  }

  /**
  * Get value of field E01CCECNM as a String.
  */
  public String getE01CCECNM()
  {
    return fieldE01CCECNM.getString();
  }

  /**
  * Set field E01CCECTI using a String value.
  */
  public void setE01CCECTI(String newvalue)
  {
    fieldE01CCECTI.setString(newvalue);
  }

  /**
  * Get value of field E01CCECTI as a String.
  */
  public String getE01CCECTI()
  {
    return fieldE01CCECTI.getString();
  }

  /**
  * Set field E01CCTID using a String value.
  */
  public void setE01CCTID(String newvalue)
  {
    fieldE01CCTID.setString(newvalue);
  }

  /**
  * Get value of field E01CCTID as a String.
  */
  public String getE01CCTID()
  {
    return fieldE01CCTID.getString();
  }

  /**
  * Set field E01CCECMR using a String value.
  */
  public void setE01CCECMR(String newvalue)
  {
    fieldE01CCECMR.setString(newvalue);
  }

  /**
  * Get value of field E01CCECMR as a String.
  */
  public String getE01CCECMR()
  {
    return fieldE01CCECMR.getString();
  }

  /**
  * Set field E01CCECCU using a String value.
  */
  public void setE01CCECCU(String newvalue)
  {
    fieldE01CCECCU.setString(newvalue);
  }

  /**
  * Get value of field E01CCECCU as a String.
  */
  public String getE01CCECCU()
  {
    return fieldE01CCECCU.getString();
  }

  /**
  * Set numeric field E01CCECCU using a BigDecimal value.
  */
  public void setE01CCECCU(BigDecimal newvalue)
  {
    fieldE01CCECCU.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E01CCECCU as a BigDecimal.
  */
  public BigDecimal getBigDecimalE01CCECCU()
  {
    return fieldE01CCECCU.getBigDecimal();
  }

  /**
  * Set field E01CCECPZ using a String value.
  */
  public void setE01CCECPZ(String newvalue)
  {
    fieldE01CCECPZ.setString(newvalue);
  }

  /**
  * Get value of field E01CCECPZ as a String.
  */
  public String getE01CCECPZ()
  {
    return fieldE01CCECPZ.getString();
  }

  /**
  * Set field E01CCEEMA using a String value.
  */
  public void setE01CCEEMA(String newvalue)
  {
    fieldE01CCEEMA.setString(newvalue);
  }

  /**
  * Get value of field E01CCEEMA as a String.
  */
  public String getE01CCEEMA()
  {
    return fieldE01CCEEMA.getString();
  }

  /**
  * Set field E01CCEPHN using a String value.
  */
  public void setE01CCEPHN(String newvalue)
  {
    fieldE01CCEPHN.setString(newvalue);
  }

  /**
  * Get value of field E01CCEPHN as a String.
  */
  public String getE01CCEPHN()
  {
    return fieldE01CCEPHN.getString();
  }

  /**
  * Set field E01CCEDIS using a String value.
  */
  public void setE01CCEDIS(String newvalue)
  {
    fieldE01CCEDIS.setString(newvalue);
  }

  /**
  * Get value of field E01CCEDIS as a String.
  */
  public String getE01CCEDIS()
  {
    return fieldE01CCEDIS.getString();
  }

  /**
  * Set field E01CCESTS using a String value.
  */
  public void setE01CCESTS(String newvalue)
  {
    fieldE01CCESTS.setString(newvalue);
  }

  /**
  * Get value of field E01CCESTS as a String.
  */
  public String getE01CCESTS()
  {
    return fieldE01CCESTS.getString();
  }

  /**
  * Set field E01CCEED using a String value.
  */
  public void setE01CCEED(String newvalue)
  {
    fieldE01CCEED.setString(newvalue);
  }

  /**
  * Get value of field E01CCEED as a String.
  */
  public String getE01CCEED()
  {
    return fieldE01CCEED.getString();
  }

  /**
  * Set field E01CCEMOV using a String value.
  */
  public void setE01CCEMOV(String newvalue)
  {
    fieldE01CCEMOV.setString(newvalue);
  }

  /**
  * Get value of field E01CCEMOV as a String.
  */
  public String getE01CCEMOV()
  {
    return fieldE01CCEMOV.getString();
  }

  /**
  * Set field E01CCEMD using a String value.
  */
  public void setE01CCEMD(String newvalue)
  {
    fieldE01CCEMD.setString(newvalue);
  }

  /**
  * Get value of field E01CCEMD as a String.
  */
  public String getE01CCEMD()
  {
    return fieldE01CCEMD.getString();
  }

  /**
  * Set field E01CCEDEN using a String value.
  */
  public void setE01CCEDEN(String newvalue)
  {
    fieldE01CCEDEN.setString(newvalue);
  }

  /**
  * Get value of field E01CCEDEN as a String.
  */
  public String getE01CCEDEN()
  {
    return fieldE01CCEDEN.getString();
  }

  /**
  * Set field E01CCEFDI using a String value.
  */
  public void setE01CCEFDI(String newvalue)
  {
    fieldE01CCEFDI.setString(newvalue);
  }

  /**
  * Get value of field E01CCEFDI as a String.
  */
  public String getE01CCEFDI()
  {
    return fieldE01CCEFDI.getString();
  }

  /**
  * Set numeric field E01CCEFDI using a BigDecimal value.
  */
  public void setE01CCEFDI(BigDecimal newvalue)
  {
    fieldE01CCEFDI.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E01CCEFDI as a BigDecimal.
  */
  public BigDecimal getBigDecimalE01CCEFDI()
  {
    return fieldE01CCEFDI.getBigDecimal();
  }

  /**
  * Set field E01CCEFBE using a String value.
  */
  public void setE01CCEFBE(String newvalue)
  {
    fieldE01CCEFBE.setString(newvalue);
  }

  /**
  * Get value of field E01CCEFBE as a String.
  */
  public String getE01CCEFBE()
  {
    return fieldE01CCEFBE.getString();
  }

  /**
  * Set numeric field E01CCEFBE using a BigDecimal value.
  */
  public void setE01CCEFBE(BigDecimal newvalue)
  {
    fieldE01CCEFBE.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E01CCEFBE as a BigDecimal.
  */
  public BigDecimal getBigDecimalE01CCEFBE()
  {
    return fieldE01CCEFBE.getBigDecimal();
  }

  /**
  * Set field E01CCEFSE using a String value.
  */
  public void setE01CCEFSE(String newvalue)
  {
    fieldE01CCEFSE.setString(newvalue);
  }

  /**
  * Get value of field E01CCEFSE as a String.
  */
  public String getE01CCEFSE()
  {
    return fieldE01CCEFSE.getString();
  }

  /**
  * Set numeric field E01CCEFSE using a BigDecimal value.
  */
  public void setE01CCEFSE(BigDecimal newvalue)
  {
    fieldE01CCEFSE.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E01CCEFSE as a BigDecimal.
  */
  public BigDecimal getBigDecimalE01CCEFSE()
  {
    return fieldE01CCEFSE.getBigDecimal();
  }

  /**
  * Set field E01CCEFCC using a String value.
  */
  public void setE01CCEFCC(String newvalue)
  {
    fieldE01CCEFCC.setString(newvalue);
  }

  /**
  * Get value of field E01CCEFCC as a String.
  */
  public String getE01CCEFCC()
  {
    return fieldE01CCEFCC.getString();
  }

  /**
  * Set numeric field E01CCEFCC using a BigDecimal value.
  */
  public void setE01CCEFCC(BigDecimal newvalue)
  {
    fieldE01CCEFCC.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E01CCEFCC as a BigDecimal.
  */
  public BigDecimal getBigDecimalE01CCEFCC()
  {
    return fieldE01CCEFCC.getBigDecimal();
  }

  /**
  * Set field E01CCEFRC using a String value.
  */
  public void setE01CCEFRC(String newvalue)
  {
    fieldE01CCEFRC.setString(newvalue);
  }

  /**
  * Get value of field E01CCEFRC as a String.
  */
  public String getE01CCEFRC()
  {
    return fieldE01CCEFRC.getString();
  }

  /**
  * Set numeric field E01CCEFRC using a BigDecimal value.
  */
  public void setE01CCEFRC(BigDecimal newvalue)
  {
    fieldE01CCEFRC.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E01CCEFRC as a BigDecimal.
  */
  public BigDecimal getBigDecimalE01CCEFRC()
  {
    return fieldE01CCEFRC.getBigDecimal();
  }

  /**
  * Set field E01CCEFRE using a String value.
  */
  public void setE01CCEFRE(String newvalue)
  {
    fieldE01CCEFRE.setString(newvalue);
  }

  /**
  * Get value of field E01CCEFRE as a String.
  */
  public String getE01CCEFRE()
  {
    return fieldE01CCEFRE.getString();
  }

  /**
  * Set numeric field E01CCEFRE using a BigDecimal value.
  */
  public void setE01CCEFRE(BigDecimal newvalue)
  {
    fieldE01CCEFRE.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E01CCEFRE as a BigDecimal.
  */
  public BigDecimal getBigDecimalE01CCEFRE()
  {
    return fieldE01CCEFRE.getBigDecimal();
  }

  /**
  * Set field E01CCEECC using a String value.
  */
  public void setE01CCEECC(String newvalue)
  {
    fieldE01CCEECC.setString(newvalue);
  }

  /**
  * Get value of field E01CCEECC as a String.
  */
  public String getE01CCEECC()
  {
    return fieldE01CCEECC.getString();
  }

  /**
  * Set field E01CCERED using a String value.
  */
  public void setE01CCERED(String newvalue)
  {
    fieldE01CCERED.setString(newvalue);
  }

  /**
  * Get value of field E01CCERED as a String.
  */
  public String getE01CCERED()
  {
    return fieldE01CCERED.getString();
  }

  /**
  * Set field E01CCEHIR using a String value.
  */
  public void setE01CCEHIR(String newvalue)
  {
    fieldE01CCEHIR.setString(newvalue);
  }

  /**
  * Get value of field E01CCEHIR as a String.
  */
  public String getE01CCEHIR()
  {
    return fieldE01CCEHIR.getString();
  }

  /**
  * Set field E01CCEAC1 using a String value.
  */
  public void setE01CCEAC1(String newvalue)
  {
    fieldE01CCEAC1.setString(newvalue);
  }

  /**
  * Get value of field E01CCEAC1 as a String.
  */
  public String getE01CCEAC1()
  {
    return fieldE01CCEAC1.getString();
  }

  /**
  * Set field E01CCEAC2 using a String value.
  */
  public void setE01CCEAC2(String newvalue)
  {
    fieldE01CCEAC2.setString(newvalue);
  }

  /**
  * Get value of field E01CCEAC2 as a String.
  */
  public String getE01CCEAC2()
  {
    return fieldE01CCEAC2.getString();
  }

  /**
  * Set field E01CCEAC3 using a String value.
  */
  public void setE01CCEAC3(String newvalue)
  {
    fieldE01CCEAC3.setString(newvalue);
  }

  /**
  * Get value of field E01CCEAC3 as a String.
  */
  public String getE01CCEAC3()
  {
    return fieldE01CCEAC3.getString();
  }

  /**
  * Set numeric field E01CCEAC3 using a BigDecimal value.
  */
  public void setE01CCEAC3(BigDecimal newvalue)
  {
    fieldE01CCEAC3.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E01CCEAC3 as a BigDecimal.
  */
  public BigDecimal getBigDecimalE01CCEAC3()
  {
    return fieldE01CCEAC3.getBigDecimal();
  }

  /**
  * Set field E01CCEAC4 using a String value.
  */
  public void setE01CCEAC4(String newvalue)
  {
    fieldE01CCEAC4.setString(newvalue);
  }

  /**
  * Get value of field E01CCEAC4 as a String.
  */
  public String getE01CCEAC4()
  {
    return fieldE01CCEAC4.getString();
  }

  /**
  * Set numeric field E01CCEAC4 using a BigDecimal value.
  */
  public void setE01CCEAC4(BigDecimal newvalue)
  {
    fieldE01CCEAC4.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E01CCEAC4 as a BigDecimal.
  */
  public BigDecimal getBigDecimalE01CCEAC4()
  {
    return fieldE01CCEAC4.getBigDecimal();
  }

  /**
  * Set field E01CCDRMM using a String value.
  */
  public void setE01CCDRMM(String newvalue)
  {
    fieldE01CCDRMM.setString(newvalue);
  }

  /**
  * Get value of field E01CCDRMM as a String.
  */
  public String getE01CCDRMM()
  {
    return fieldE01CCDRMM.getString();
  }

  /**
  * Set numeric field E01CCDRMM using a BigDecimal value.
  */
  public void setE01CCDRMM(BigDecimal newvalue)
  {
    fieldE01CCDRMM.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E01CCDRMM as a BigDecimal.
  */
  public BigDecimal getBigDecimalE01CCDRMM()
  {
    return fieldE01CCDRMM.getBigDecimal();
  }

  /**
  * Set field E01CCDRDD using a String value.
  */
  public void setE01CCDRDD(String newvalue)
  {
    fieldE01CCDRDD.setString(newvalue);
  }

  /**
  * Get value of field E01CCDRDD as a String.
  */
  public String getE01CCDRDD()
  {
    return fieldE01CCDRDD.getString();
  }

  /**
  * Set numeric field E01CCDRDD using a BigDecimal value.
  */
  public void setE01CCDRDD(BigDecimal newvalue)
  {
    fieldE01CCDRDD.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E01CCDRDD as a BigDecimal.
  */
  public BigDecimal getBigDecimalE01CCDRDD()
  {
    return fieldE01CCDRDD.getBigDecimal();
  }

  /**
  * Set field E01CCDRYY using a String value.
  */
  public void setE01CCDRYY(String newvalue)
  {
    fieldE01CCDRYY.setString(newvalue);
  }

  /**
  * Get value of field E01CCDRYY as a String.
  */
  public String getE01CCDRYY()
  {
    return fieldE01CCDRYY.getString();
  }

  /**
  * Set numeric field E01CCDRYY using a BigDecimal value.
  */
  public void setE01CCDRYY(BigDecimal newvalue)
  {
    fieldE01CCDRYY.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E01CCDRYY as a BigDecimal.
  */
  public BigDecimal getBigDecimalE01CCDRYY()
  {
    return fieldE01CCDRYY.getBigDecimal();
  }

  /**
  * Set field E01CCDRUS using a String value.
  */
  public void setE01CCDRUS(String newvalue)
  {
    fieldE01CCDRUS.setString(newvalue);
  }

  /**
  * Get value of field E01CCDRUS as a String.
  */
  public String getE01CCDRUS()
  {
    return fieldE01CCDRUS.getString();
  }

  /**
  * Set field E01CCDMMM using a String value.
  */
  public void setE01CCDMMM(String newvalue)
  {
    fieldE01CCDMMM.setString(newvalue);
  }

  /**
  * Get value of field E01CCDMMM as a String.
  */
  public String getE01CCDMMM()
  {
    return fieldE01CCDMMM.getString();
  }

  /**
  * Set numeric field E01CCDMMM using a BigDecimal value.
  */
  public void setE01CCDMMM(BigDecimal newvalue)
  {
    fieldE01CCDMMM.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E01CCDMMM as a BigDecimal.
  */
  public BigDecimal getBigDecimalE01CCDMMM()
  {
    return fieldE01CCDMMM.getBigDecimal();
  }

  /**
  * Set field E01CCDMDD using a String value.
  */
  public void setE01CCDMDD(String newvalue)
  {
    fieldE01CCDMDD.setString(newvalue);
  }

  /**
  * Get value of field E01CCDMDD as a String.
  */
  public String getE01CCDMDD()
  {
    return fieldE01CCDMDD.getString();
  }

  /**
  * Set numeric field E01CCDMDD using a BigDecimal value.
  */
  public void setE01CCDMDD(BigDecimal newvalue)
  {
    fieldE01CCDMDD.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E01CCDMDD as a BigDecimal.
  */
  public BigDecimal getBigDecimalE01CCDMDD()
  {
    return fieldE01CCDMDD.getBigDecimal();
  }

  /**
  * Set field E01CCDMYY using a String value.
  */
  public void setE01CCDMYY(String newvalue)
  {
    fieldE01CCDMYY.setString(newvalue);
  }

  /**
  * Get value of field E01CCDMYY as a String.
  */
  public String getE01CCDMYY()
  {
    return fieldE01CCDMYY.getString();
  }

  /**
  * Set numeric field E01CCDMYY using a BigDecimal value.
  */
  public void setE01CCDMYY(BigDecimal newvalue)
  {
    fieldE01CCDMYY.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E01CCDMYY as a BigDecimal.
  */
  public BigDecimal getBigDecimalE01CCDMYY()
  {
    return fieldE01CCDMYY.getBigDecimal();
  }

  /**
  * Set field E01CCDMTI using a String value.
  */
  public void setE01CCDMTI(String newvalue)
  {
    fieldE01CCDMTI.setString(newvalue);
  }

  /**
  * Get value of field E01CCDMTI as a String.
  */
  public String getE01CCDMTI()
  {
    return fieldE01CCDMTI.getString();
  }

  /**
  * Set field E01CCDMUS using a String value.
  */
  public void setE01CCDMUS(String newvalue)
  {
    fieldE01CCDMUS.setString(newvalue);
  }

  /**
  * Get value of field E01CCDMUS as a String.
  */
  public String getE01CCDMUS()
  {
    return fieldE01CCDMUS.getString();
  }

}